replicaCount: 1

route:
  enabled: true

containerEnv:
  - name: LOG_LEVEL
    value: "DEBUG"

image:
  repository: image-registry.openshift-image-registry.svc:5000
  tag: latest
  pullPolicy: Always


resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 90
  failureThreshold: 10
  timeoutSeconds: 90
  periodSeconds: 60
  successThreshold: 1

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 90
  failureThreshold: 10
  timeoutSeconds: 90
  periodSeconds: 60
  successThreshold: 1