resources:
  - all.yaml
commonLabels:
  app: kustomize-label
patches:
- target:
    name: basic-spring-boot-dev
    kind: ImageStream
    version: v1
  patch: |-
    - op: replace
      path: /metadata/labels/partition
      value: customerB
- target:
    name: basic-spring-boot-dev
    kind: ImageStream
    version: v1
  patch: |-
    - op: remove
      path: /metadata/labels/release